### PR TITLE
Instead of being a efi app, it's a efi bootloader

### PR DESCRIPTION
**Pull request by PokeyManatee4**
I made it actually boot something

### CODE REVIEW

**Review by kevinalavik — CHANGES_REQUESTED** [review]
1. Dont put everything in the single boot.c file 2. We havent talked about a boot protocol yet afaik, we would need to discuss that. 3. Seperate UEFI bootloader and legacy. Have like arch/x86_64-uefi and arch/x86_64-pc. 

I would put this on hold since we havent disccussed much about the bootloader. We will see when azzy wakes up

**Review by laurinyev — CHANGES_REQUESTED** [review]
You just copied Poncho, then removed everything

Context: he made a tutorial lol

**Comment by laurinyev** [comment]
I recognize taht code lmfao

**Comment by PokeyManatee4** [comment]
Its a basic efi bootloader, as i told Kevin, it copies the kernel to ram,
verifies it's a elf then executes it :/

**Comment by PokeyManatee4** [comment]
He made a turo, it's a basic kernel loader

**Pull request closed without merging**
